baseURL = 'https://williamxli.com/'
languageCode = 'en-us'
title = 'William Li'
theme = "SimpleIntro"

publishDir = "public"

[params]
    mainbg = "https://cdn.discordapp.com/attachments/704599857083449366/722677588484423721/luca-bravo-XJXWbfSo2f0-unsplash_1.jpg"
    name = "William Li"
    mainTitle = "Hello, I'm William."
    mainText = "Software Engineer || Foodie"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Experience"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"
    [[menu.main]]
        identifier = "resume"
        name = "Resume"
        url = "files/William_Li_Resume.pdf"